//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class district
    {
        public district()
        {
            this.students = new HashSet<student>();
        }
    
        public string id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<student> students { get; set; }
    }
}
