//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace connection
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class student
    {
        public int id { get; set; }

        [Required(ErrorMessage="El Nombre es Requerido")]
        public string first_name { get; set; }

        [Required(ErrorMessage = "El Apellido es Requerido")]
        public string last_name { get; set; }
                
        public string full_name { get; set; }

        [Required(ErrorMessage = "El E-mail es Requerido")]
        [EmailAddress(ErrorMessage="E-mail no Válido")]
        public string email { get; set; }

        [Required(ErrorMessage = "El Distrito es Requerido")]
        public string district_id { get; set; }
    
        public virtual district district { get; set; }

        public void setFullNameAttribute()
        {
            this.full_name = this.last_name + " " + this.first_name;
        }
    }
}
